# Generated by Django 3.1.8 on 2021-04-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Isbn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OtherTitle', models.CharField(max_length=255)),
                ('SN', models.CharField(default=2302251235, max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='bookStore.Category'),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='isbn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookStore.isbn'),
        ),
    ]
