# Generated by Django 3.1.8 on 2021-04-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0002_auto_20210422_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='SN',
            field=models.CharField(default=6892326278, max_length=10, unique=True),
        ),
    ]
