# Generated by Django 3.1.8 on 2021-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0005_auto_20210424_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='SN',
            field=models.CharField(default=9738499634, max_length=10, unique=True),
        ),
    ]
